### ISSUE TITLE
Memory leak (Lab7.c)

### ISSUE THREAD

**Issue by sergio-nsk** [danilproger/Labs#4]
https://github.com/danilproger/Labs/blob/81fe93ace356379216e7bc31f76a98dad93567ad/Lab7.c#L103
https://github.com/danilproger/Labs/blob/81fe93ace356379216e7bc31f76a98dad93567ad/Lab7.c#L109

`visited` и `topSorted` не освобождают память в конце `main`.

**Comment by danilproger** [comment]
Точно, их забыл очистить
